server.port=8080

# LLVMTA 安装目录。
# 不填写时，LlvmtaRunner 默认使用：
# /home/当前用户/llvmta
llvmta.home=${LLVMTA_HOME:}

# LLVMTA 调用脚本
llvmta.script=${LLVMTA_SCRIPT:runf.py}

# Python 命令
llvmta.python=${LLVMTA_PYTHON:python3}

# 启动前配置
#export LLVMTA_HOME=/opt/isure/llvmta
#mvn spring-boot:run